### ISSUE TITLE
Full compatibility with PHP 7

### ISSUE THREAD

**Issue by bkosun** [lestor/kohana#1]
**Is your feature request related to a problem? Please describe**
Active support for PHP 5 was discontinued January 19, 2017, and security support will be terminated December 31, 2018.

**Describe the solution you'd like**

- Drop PHP 5 support;
- Do not use functions that have been deprecated.

Issues:
- [x] #2 Install MySQLi driver as default driver for MySQL enhancement
- [x] #8 Install Sodium encryption engine as default enhancement 
- [x] #9 Update error handlers to strictly comply with PHP 7 enhancement
- [x] #21 Fix Unit Tests

http://php.net/supported-versions.php
http://php.net/manual/ru/doc.changelog.php

**Comment by bkosun** [comment]
#3
